/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brde.tlpcalculator;

import java.util.Calendar;

/**
 *
 * @author molfetti
 */
public class TelaTLP extends javax.swing.JFrame {

    /**
     * Creates new form TelaTLP
     */
    public TelaTLP() {
        initComponents();
        float cdc;
        float spread;
        float tlp;
        panInfoJuros.setVisible(false);
        panInfoNTN.setVisible(false);
        panInfoIPCA.setVisible(false);
        panInfoFixo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCDC = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtBNDES = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lblJuros = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIPCA = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtTLP = new javax.swing.JSpinner();
        btnIPCA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblVariavel = new javax.swing.JLabel();
        lblFixo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnJuros = new javax.swing.JButton();
        btnFixo = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panInfoNTN = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNTN1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panInfoJuros = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panInfoIPCA = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        panInfoFixo = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TLP CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CDC do BRDE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Spread do BNDES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));

        txtCDC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCDC.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.5f));
        getContentPane().add(txtCDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("TLP do mês");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        txtBNDES.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBNDES.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.5f));
        txtBNDES.setMaximumSize(new java.awt.Dimension(33, 28));
        getContentPane().add(txtBNDES, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TAXA DE JUROS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 308, -1, 20));

        lblJuros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJuros.setForeground(new java.awt.Color(0, 51, 204));
        lblJuros.setText("0,0000");
        lblJuros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJurosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJurosMouseExited(evt);
            }
        });
        getContentPane().add(lblJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 308, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("% a.a.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 467, -1, 30));

        txtIPCA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIPCA.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.5f));
        getContentPane().add(txtIPCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("NTN-B 5a (média 3 meses)");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        txtTLP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTLP.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.5f));
        txtTLP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTLP.setMaximumSize(new java.awt.Dimension(33, 28));
        getContentPane().add(txtTLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, -1));

        btnIPCA.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnIPCA.setText("CALCULAR IPCA");
        btnIPCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPCAActionPerformed(evt);
            }
        });
        getContentPane().add(btnIPCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("IPCA (mediana FOCUS)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 517, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("compoenente variável");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 537, -1, -1));

        lblVariavel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVariavel.setForeground(new java.awt.Color(0, 51, 204));
        lblVariavel.setText("0,0000");
        getContentPane().add(lblVariavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 527, -1, -1));

        lblFixo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFixo.setForeground(new java.awt.Color(0, 51, 204));
        lblFixo.setText("0,0000");
        getContentPane().add(lblFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 467, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("% a.a.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 527, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("% a.a.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 308, -1, 20));

        btnJuros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnJuros.setText("CALCULAR JUROS");
        btnJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurosActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 259, -1, -1));

        btnFixo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnFixo.setText("CALCULAR FIXO");
        btnFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 140, -1));

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        panInfoNTN.setBackground(new java.awt.Color(204, 204, 255));
        panInfoNTN.setForeground(new java.awt.Color(204, 0, 0));
        panInfoNTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panInfoNTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panInfoNTNMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("<html>divuldada no último dia do mês pelo BACEN<br> \n(média aritimética simples diária (3 últimos <br>\nmeses) relativos aos vértices de 5 anos da <br>\nestrutura a termo da NTN-B</html>");

        javax.swing.GroupLayout panInfoNTNLayout = new javax.swing.GroupLayout(panInfoNTN);
        panInfoNTN.setLayout(panInfoNTNLayout);
        panInfoNTNLayout.setHorizontalGroup(
            panInfoNTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoNTNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panInfoNTNLayout.setVerticalGroup(
            panInfoNTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panInfoNTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 50));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setText("developed by Molfetti");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 565, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/brde.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("IPCA (mediana FOCUS)");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 409, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("% a.a.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("% a.a.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("% a.a.");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 30));

        txtNTN1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNTN1.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.5f));
        getContentPane().add(txtNTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("% a.a.");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("% a.a.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 50));

        panInfoJuros.setBackground(new java.awt.Color(204, 204, 255));
        panInfoJuros.setForeground(new java.awt.Color(204, 0, 0));
        panInfoJuros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panInfoJurosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panInfoJurosMouseExited(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("((1+CDC)*(1+Spread)*(1+TLP)-1)");

        javax.swing.GroupLayout panInfoJurosLayout = new javax.swing.GroupLayout(panInfoJuros);
        panInfoJuros.setLayout(panInfoJurosLayout);
        panInfoJurosLayout.setHorizontalGroup(
            panInfoJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoJurosLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        panInfoJurosLayout.setVerticalGroup(
            panInfoJurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoJurosLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(panInfoJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Componente Fixo");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, 30));

        panInfoIPCA.setBackground(new java.awt.Color(204, 204, 255));
        panInfoIPCA.setForeground(new java.awt.Color(204, 0, 0));
        panInfoIPCA.setName(""); // NOI18N
        panInfoIPCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panInfoIPCAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panInfoIPCAMouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("<html>divuldada no Boletim FOCUS do Bacen  <br> <link>https://www.bcb.gov.br/pec/GCI/PORT/readout/readout.asp</link></html>");

        javax.swing.GroupLayout panInfoIPCALayout = new javax.swing.GroupLayout(panInfoIPCA);
        panInfoIPCA.setLayout(panInfoIPCALayout);
        panInfoIPCALayout.setHorizontalGroup(
            panInfoIPCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoIPCALayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );
        panInfoIPCALayout.setVerticalGroup(
            panInfoIPCALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panInfoIPCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 330, 30));

        panInfoFixo.setBackground(new java.awt.Color(204, 204, 255));
        panInfoFixo.setForeground(new java.awt.Color(204, 0, 0));
        panInfoFixo.setName(""); // NOI18N
        panInfoFixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panInfoFixoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panInfoFixoMouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("<html>((1+CDC)*(1+Spread)*(1+Taxa-pré)-1)<br>\nTaxa-pré = parte da TLP que se torna fixa após a contratação<br>\n(NTN-B * fator de ajuste</html>");

        javax.swing.GroupLayout panInfoFixoLayout = new javax.swing.GroupLayout(panInfoFixo);
        panInfoFixo.setLayout(panInfoFixoLayout);
        panInfoFixoLayout.setHorizontalGroup(
            panInfoFixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoFixoLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        panInfoFixoLayout.setVerticalGroup(
            panInfoFixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(panInfoFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurosActionPerformed
        // TODO add your handling code here:
        float cdc = (float) txtCDC.getValue();
        float spread = (float) txtBNDES.getValue();
        float tlp = (float) txtTLP.getValue();
        float juros = (((cdc/100+1)*(spread/100+1)*(tlp/100+1))-1)*100;
        lblJuros.setText(String.format("%.4f",juros));
        
        
    }//GEN-LAST:event_btnJurosActionPerformed

    private void btnIPCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIPCAActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        int year = cal.get(Calendar.YEAR);
        float ntn = (float) txtNTN1.getValue();
        
        float cdc = (float) txtCDC.getValue();
        float spread = (float) txtBNDES.getValue();
        float tlp = (float) txtTLP.getValue();
        String ajuste;
        
        switch (year) {
            case 2018:
                {
                    ajuste = "0.57";
                    break;
                }
            case 2019:
                {
                    ajuste = "0.66";
                    break;
                }
            case 2020:
                {
                    ajuste = "0.74";
                    break;
                }
            case 2021:
                {
                    ajuste = "0.83";
                    break;
                }
            case 2022:
                {
                    ajuste = "0.91";
                    break;
                }
            default:
                {
                    ajuste = "1.00";
                    break;
                }
        }
        
        float taxapre = (Float.parseFloat(ajuste))*ntn;
        float fixo = (((cdc/100+1)*(spread/100+1)*(taxapre/100+1))-1)*100;
        lblFixo.setText(String.format("%.4f",fixo));
        float var = (((tlp/100+1)/(taxapre/100+1))-1)*100;
        lblVariavel.setText(String.format("%.4f",var));
        
    }//GEN-LAST:event_btnIPCAActionPerformed

    private void btnFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixoActionPerformed
        // TODO add your handling code here:
        float cdc = (float) txtCDC.getValue();
        float spread = (float) txtBNDES.getValue();
        float tlp = (float) txtTLP.getValue();
        float var = (float) txtIPCA.getValue();
        lblVariavel.setText(String.format("%.4f",var));
        float taxapre = (((tlp/100+1)/(var/100+1))-1)*100;
        float fixo = (((cdc/100+1)*(spread/100+1)*(taxapre/100+1))-1)*100;
        lblFixo.setText(String.format("%.4f",fixo));
        
    }//GEN-LAST:event_btnFixoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtCDC.setValue(0);
        txtBNDES.setValue(0);
        txtTLP.setValue(0);
        txtIPCA.setValue(0);
        txtIPCA.setValue(0);
        lblJuros.setText(String.format("0,0000"));
        lblVariavel.setText(String.format("0,0000"));
        lblFixo.setText(String.format("0,0000"));
    }//GEN-LAST:event_btnResetActionPerformed

    private void lblJurosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJurosMouseEntered
        panInfoJuros.setVisible(true);
    }//GEN-LAST:event_lblJurosMouseEntered

    private void lblJurosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJurosMouseExited
        // TODO add your handling code here:
        panInfoJuros.setVisible(false);
    }//GEN-LAST:event_lblJurosMouseExited

    private void panInfoJurosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoJurosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoJurosMouseEntered

    private void panInfoJurosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoJurosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoJurosMouseExited

    private void panInfoNTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoNTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoNTNMouseEntered

    private void panInfoNTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoNTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoNTNMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        panInfoNTN.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        panInfoNTN.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseExited

    private void panInfoIPCAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoIPCAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoIPCAMouseEntered

    private void panInfoIPCAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoIPCAMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoIPCAMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        panInfoIPCA.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        panInfoIPCA.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseExited

    private void panInfoFixoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoFixoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoFixoMouseEntered

    private void panInfoFixoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoFixoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panInfoFixoMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        panInfoFixo.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        panInfoFixo.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTLP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTLP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTLP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTLP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTLP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFixo;
    private javax.swing.JButton btnIPCA;
    private javax.swing.JButton btnJuros;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFixo;
    private javax.swing.JLabel lblJuros;
    private javax.swing.JLabel lblVariavel;
    private javax.swing.JPanel panInfoFixo;
    private javax.swing.JPanel panInfoIPCA;
    private javax.swing.JPanel panInfoJuros;
    private javax.swing.JPanel panInfoNTN;
    private javax.swing.JSpinner txtBNDES;
    private javax.swing.JSpinner txtCDC;
    private javax.swing.JSpinner txtIPCA;
    private javax.swing.JSpinner txtNTN1;
    private javax.swing.JSpinner txtTLP;
    // End of variables declaration//GEN-END:variables
}
